# Generated by Django 6.0.1 on 2026-02-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid_lessons",
            new_name="paid_lesson",
        ),
    ]
