# Generated by Django 6.0.1 on 2026-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_paid_lessons_payment_paid_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="strip_price_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="strip_product_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="strip_session_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
